<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up(): void
    {
        Schema::table('entry_instructions', function (Blueprint $table) {
            // Safely drop the old foreign key and column if they exist
            if (Schema::hasColumn('entry_instructions', 'lot_number')) {
                try {
                    // The foreign key name is auto-generated by Laravel, so we'll use the column name to drop it
                    $table->dropForeign(['lot_number']);
                } catch (\Exception $e) {
                    // If the foreign key doesn't exist, we can ignore the error
                }
                $table->dropColumn('lot_number');
            }

            // Add new frn_id column and foreign key if they don't exist
            if (!Schema::hasColumn('entry_instructions', 'frn_id')) {
                $table->string('frn_id')->after('id');
                $table->foreign('frn_id')->references('lot_number')->on('frns')->cascadeOnDelete();
            }

            // Add new columns if they don't exist
            if (!Schema::hasColumn('entry_instructions', 'instruction_type')) {
                $table->string('instruction_type')->after('frn_id');
            }
            if (!Schema::hasColumn('entry_instructions', 'details')) {
                $table->text('details')->nullable()->after('instruction_type');
            }

            // Update status column
            $table->string('status')->default('pending')->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down(): void
    {
        Schema::table('entry_instructions', function (Blueprint $table) {
            // Revert status column
            $table->string('status')->default('Processing Initiated')->change();

            // Drop new columns and foreign key if they exist
            if (Schema::hasColumn('entry_instructions', 'frn_id')) {
                $table->dropForeign(['frn_id']);
                $table->dropColumn('frn_id');
            }
            if (Schema::hasColumn('entry_instructions', 'instruction_type')) {
                $table->dropColumn('instruction_type');
            }
            if (Schema::hasColumn('entry_instructions', 'details')) {
                $table->dropColumn('details');
            }

            // Re-add old lot_number column and foreign key if they don't exist
            if (!Schema::hasColumn('entry_instructions', 'lot_number')) {
                $table->string('lot_number')->unique();
                $table->foreign('lot_number')->references('lot_number')->on('frns')->cascadeOnDelete();
            }
        });
    }
};
